# Generated by Django 3.0.5 on 2022-07-12 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appreclamo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Arreglos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fecha_arreglo', models.DateField()),
                ('Arreglo_1', models.CharField(blank=True, max_length=150)),
                ('Arreglo_2', models.CharField(blank=True, max_length=150)),
                ('Arreglo_3', models.CharField(blank=True, max_length=150)),
                ('Arreglo_4', models.CharField(blank=True, max_length=150)),
                ('Trabajado_por_1', models.CharField(blank=True, max_length=80)),
                ('Trabajado_por_2', models.CharField(blank=True, max_length=80)),
                ('Trabajado_por_3', models.CharField(blank=True, max_length=80)),
                ('observacion', models.CharField(blank=True, max_length=150)),
                ('cod_reclamo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appreclamo.Reclamos')),
            ],
        ),
    ]
